### PR TITLE
Data download features

### PR DESCRIPTION
**Pull request by twelch**
Allows users to download data in CSV and JSON format from reports

Use cases:
- [x] Can be added to table component for exporting the table as CSV
- [x] Can be added to top of report for exporting the whole function result to JSON
- [x] Can be added to top of report section for exporting a set of bite-size charts/tables to one larger CSV

Requirements:
- [x] UI is a kebab dropdown menu that takes array-based table data and transforms to CSV and JSON as-is
- [x] Data is expected to be an array of objects, and standard formatters for JSON and CSV.  CSV will extract the header names.  Flattening is automatic.

small-download

### CODE REVIEW

**Comment by underbluewaters** [comment]
Once we have the table component it would be nice to build the configuration of this button off of the table component configuration, so that an author need only specify { enableCSV: true } to get a button in a standard location. I'm not sure whether JSON needs to be included here.

For JSON output, I was thinking more along the lines of what SeaSketch currently has in the MPATT project with a top-level export option for the entire reporting output of a Sketch or Collection. In legacy SeaSketch this can be accessed from both a context menu action and the report sidebar itself. This is not enabled on all projects, IIRC because the automated output is quite cryptic and oddly organized due to the fact that we don't have a lot of control in ArcGIS Server.

Screen Shot 2021-03-08 at 6 56 59 AM

Screen Shot 2021-03-08 at 6 57 53 AM

This would be a lot more tricky to implement, since we specify the contents of the report using ReportCard and useFunction hooks. There would have to be some runtime trickery done to collect that info. It also requires some coordination between the report iframe and the surrounding SeaSketch App. Maybe the surrounding app can issue a postMessage request for output? This is something I think we can plan to include for SeaSketch Next, rather than bolt onto current SeaSketch.

**Comment by twelch** [comment]
Here's an example where I don't think we want a simple export button per table because they are really a group of bite size table. Rather we want an export to CSV for the whole set
image

**Comment by underbluewaters** [comment]
Ah interesting. I guess in this case... oh boy yeah that does require some very context specific decisions.

**Comment by twelch** [comment]
One could argue those bite-sized tables should become one 'group' table if they are being generated from the same function result and have the same data shape.  I'll look closer at it.  Maybe I can start with the simplest and gather feedback.

**Pull request merged**
